### ISSUE TITLE
IndexedProperty::at() with default value

### ISSUE THREAD

**Issue by speleo3** [schrodinger/maeparser#12]
I suggest to add the following method:

```c++
    const T& IndexedProperty::at(size_type index, const T& default_) const
    {
        if (m_is_null && (*m_is_null)[index]) {
            return default_;
        }
        return m_data[index];
    }
```

I would use it kind of like [dict.get](https://docs.python.org/3/library/stdtypes.html#dict.get) in Python.

**Comment by lorton** [comment]
@speleo3 - this is reasonable, can you add it and submit a pull request?  Also, should it be:
`m_is_null || (*m_is_null)[index])` instead of `&&`?

**Comment by speleo3** [comment]
@lorton - `&&` is correct, it only dereferences `m_is_null` if it exists (I copied that line from the raising method).
