### ISSUE TITLE
non-raising IndexedBlocked::getStringProperty(name)

### ISSUE THREAD

**Issue by speleo3** [schrodinger/maeparser#13]
`IndexedBlocked::getStringProperty` (as well as bool, int, real versions) raises an exception if the key is not found. However, since the method returns a (shared) pointer, it could also return `nullptr`. In particular, this would allow usage of `auto`. Consider this:

Current version:
```c++
std::shared_ptr<IndexedStringProperty> my_prop;
if (block->hasStringProperty("s_my_prop")) {
    my_prop = block->getStringProperty("s_my_prop");
}
for (size_t i = 0; ...) {
    if (my_prop) {
        std::cout << "My Property: " << my_prop.at(i) << std::endl;
    } else {
        std::cout << "My Property: <unset>" << std::endl;
    }
}
```
Versus:
```c++
auto my_prop = block->getStringPropertyNonRaising("s_my_prop");
for (size_t i = 0; ...) {
    if (my_prop) {
        std::cout << "My Property: " << my_prop.at(i) << std::endl;
    } else {
        std::cout << "My Property: <unset>" << std::endl;
    }
}
```
Or, in combination with #12 (or something similar), it could even return an all-missing property:
```c++
auto my_prop = block->getStringPropertyOptional("s_my_prop");
for (size_t i = 0; ...) {
    std::cout << "My Property: " << my_prop.at(i, "<unset>") << std::endl;
}
```

**Comment by lorton** [comment]
@mbeachy / @torcolvin - thoughts on changing the interface as such?  I've also noticed the usability annoyance described here in using this code.
