### ISSUE TITLE
SOVERSION?

### ISSUE THREAD

**Issue by smoe** [schrodinger/maeparser#22]
Hello,

Many thanks for your support of Open Source software. We are all very much aware of what you are doing for PyMOL - all much appreciated. I was about to package maeparser for Debian. In an ideal world you would trust the packages we are providing for these distributions and may in some cases even decide to link dynamically against these. In that spirit, I thought I come back with this smaller issue at hand that would nonetheless be important for anyone executing a binary you compiled dynamically against your own library on a regular Linux machine.

You are certainly aware of libraries having an SONAME. This expresses binary compatibility between versions of the dynamic library. And it is also common for that SONAME to be versioned. The wikipedia page
[https://en.wikipedia.org/wiki/Soname](https://en.wikipedia.org/wiki/Soname)
explains it nicely. To add a version, you can set a SOVERSION with cmake. May I presume that to be 0 ? Shall I craft a patch?

I have understood from the readme that you do not expect many changes to that library and may hence have intentionally decided against the specification of a version, but that would be unfortunate. 

```
$ objdump -p build/libmaeparser.so |grep -i so
build/libmaeparser.so:     file format elf64-x86-64
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  SONAME               libmaeparser.so
```

Many thanks and kind regards,

Steffen

**Comment by lorton** [comment]
Hi @smoe - as far as I know the lack of a SONAME is simply an oversight at this point -- we will likely in fact want one in order to differentiate between this version and later versions where we intend to also include a mae writer.  I'll confirm this is true with our developers today, but I'm pretty sure it is.  If you don't mind contributing I'd certainly be happy to take a pull request adding this.

Thanks,
Pat

**Comment by smoe** [comment]
This is what it looks like with PR #23 applied:
```
$ objdump -p build/libmaeparser.so |grep -i so
build/libmaeparser.so:     file format elf64-x86-64
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  SONAME               libmaeparser.so.1
```
and the files created are
```
$ ls -l build/lib*
lrwxrwxrwx 1 moeller moeller      17 Oct  4 12:21 build/libmaeparser.so -> libmaeparser.so.1
lrwxrwxrwx 1 moeller moeller      21 Oct  4 12:21 build/libmaeparser.so.1 -> libmaeparser.so.1.0.1
-rwxr-xr-x 1 moeller moeller 4443792 Oct  4 12:21 build/libmaeparser.so.1.0.1
```
Cheers,
Steffen

**Comment by lorton** [comment]
Closing after merging PR submitted by @smoe - thanks again.
