### ISSUE TITLE
README could possibly describe Maestro's advantages, Debian description review, RRID 

### ISSUE THREAD

**Issue by smoe** [schrodinger/maeparser#24]
Hello,

I am about to wrap up the Debian package for your 1.0.1 release (plus the SOVERSION patch). This package will migrate to Ubuntu and other derivatives of Debian, too, so there are some folks rather likely to see it and search engines help. I really wanted to describe the package as nicely as I could, but, well, I do not know too much about the Maestro file format and do not want to write anything wrong about it. If it is easy for you, could you possibly extend your README.md with a bit of a description on why that format is important? From there I would copy bits to [https://salsa.debian.org/science-team/schroedinger-maeparser/blob/master/debian/control](https://salsa.debian.org/science-team/schroedinger-maeparser/blob/master/debian/control) and ping you again to OK it, if you don't mind. Alternatively, which strategically for the positioning of Linux distributions in the industrial scientific world would make me very happy, you can also send pull requests to that package description ("control") file directly or have write access to it.

There is something else. To allow references to your parser, already published or not ( I would have an appropriate academic Open Source journal for you if in doubt, which I think is nice since it allows to explain bits and pieces that cannot be transported to the community via the typical booths on conferences) the Research Identifiers have emerged. Please kindly point your marketing department to https://www.scicrunch.org (and bio.tools and OMICtools.com). For your maeparser please fill out https://scicrunch.org/create/resource yourselves. You should have a reply with a RRID within a working day. Debian adds this info to its package description - we are pretty completely covering the bioinformatics tools for which the RRIDs have emerged, the other disciplines (cheminformatics in particular) are following (slowly).

Many thanks and regards,

Steffen

**Comment by lorton** [comment]
Hi Steffen - I've added a 'Why this format' section to the readme and put it up for code review.  I've also registered the project with scicrunch.org.

**Comment by smoe** [comment]
Addressed in https://github.com/schrodinger/maeparser/pull/26 - many thanks! Steffen
