### ISSUE TITLE
Hard-coded to build libmaeparser as SHARED

### ISSUE THREAD

**Issue by e-kwsm** [schrodinger/maeparser#56]
https://github.com/schrodinger/maeparser/blob/05fb8312b1d3ad6c8a5b544ef0f7fac80ee5ed9e/CMakeLists.txt#L26

Therefore, an external project cannot build static libmaeparser unless the file is modified.
See openbabel/openbabel#2089.

**Comment by lorton** [comment]
Thanks for filing @e-kwsm - assigning to you for hopefully a quick fix @ricrogz

**Comment by e-kwsm** [comment]
Now we can build maeparser statically. Thank you.
